# Generated by Django 3.0.4 on 2020-03-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
